version: "3.9"

services:
  django:
    build:
      context: .
    ports:
      - "8001:8000"
    networks:
      - postgres
    depends_on:
      - database
  
  database:
    container_name: db
    image: postgres:13.4-alpine
    restart: always
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    ports:
      - 5433:5432
    networks:
      - postgres

volumes:
  pgdata:

networks:
  postgres: