# Generated by Django 4.2.1 on 2023-06-04 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='status',
            field=models.CharField(default='Ativo', max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(default='Ativo', max_length=15),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 1, 32, 34, 382285, tzinfo=datetime.timezone.utc)),
        ),
    ]
