# Generated by Django 4.2.1 on 2023-06-05 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_usuarios', '0002_grupo_status_usuario_status_alter_grupo_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
